package application;

import java.io.IOException;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class controller2 {
	@FXML
	private TextField idNumVuelo;
	@FXML
	private TextField idCidOrigen;
	@FXML
	private TextField idCidDestino;
	@FXML
	private TextField idCodAvion;
	@FXML
	private Button idSiguiente2;
	@FXML
	private Button idAtras1;

	// Event Listener on Button[#idSiguiente2].onMouseClicked
	@FXML
	public void clicSiguiente2(MouseEvent event) throws IOException {
		// TODO Autogenerated
	AbrirVentanaFinal vf = new AbrirVentanaFinal();
	vf.show((Stage) idSiguiente2.getScene().getWindow());	
	}

	
	
	// Event Listener on Button[#idAtras1].onMouseClicked
	@FXML
	public void clicAtras1(MouseEvent event) throws IOException {
		// TODO Autogenerated
		
		AbrirVentanaPrimaria vp = new AbrirVentanaPrimaria();
		vp.show((Stage) idAtras1.getScene().getWindow());
	}
}
