package application;

import java.io.IOException;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class controller1 {
	@FXML
	private TextField txtAerolinea;
	@FXML
	private TextField txtCodigo;
	@FXML
	private TextField txtNacionalidad;
	@FXML
	private Button btnSiguiente1;

	// Event Listener on Button[#btnSiguiente1].onMouseClicked
	@FXML
	public void clicSiguiente1(MouseEvent event) throws IOException {
		// TODO Autogenerated
		
		AbrirVentanaSecundaria vs = new AbrirVentanaSecundaria();
		vs.show((Stage) btnSiguiente1.getScene().getWindow());

		
	}
}
